version: '3.3'

services:
  web:
    image: superpagos_api
    container_name: 'superpagos_api'
    build:
      context: .
      dockerfile: Dockerfile.node.netcore
      args:
        PROJECT_NAME: Web
    ports:
      - "80:5000"
      - "5000:5000"
    environment:
      DefaultConnection: Server=postgres;Database=hangfire;User Id=sa;Password=password;Port=5432;
    env_file:
      - .env
      
  scheduler:
    image: scheduler
    container_name: "superpagos_scheduler"
    build:
      context: .
      args:
      - PROJECT_NAME=Scheduler
      - CONFIGURATION=Release
      dockerfile: Dockerfile.netcore
    ports:
    - "8080:5000"
    environment:
      HangfireConnection: Server=postgres_hangfire;Database=hangfire;User Id=sa;Password=password;Port=5432;
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/hangfire"]
      interval: 30s
      timeout: 5s
      retries: 3

  migrations:
    image: web_migrations
    container_name: "web_migrations"
    build:
      context: .
      dockerfile: Dockerfile.migrations
      args:
        PROJECT_NAME: Web
    environment:
      DefaultConnection: Server=postgres;Database=superpagos;User Id=sa;Password=password;Port=5432;

  postgres:
    image: postgres:11
    container_name: "postgres"
    restart: unless-stopped
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: sa
      POSTGRES_DB: superpagos
      POSTGRES_HOST: postgres
    volumes:
    - superpagos_data:/var/lib/postgresql/data
    
  postgres_hangfire:
    image: postgres:11
    container_name: "postgres_hangfire"
    restart: unless-stopped
    ports:
    - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: sa
      POSTGRES_DB: hangfire
      POSTGRES_HOST: postgres_hangfire
    volumes:
    - hangfire_data:/var/lib/postgresql/data  
    
networks:
  default:
    external:
      name: superpagos_network

volumes:
  superpagos_data:
    external: true
  hangfire_data:
    external: true