FROM docker.elastic.co/beats/filebeat:6.5.4
USER root
COPY ./filebeat.config.yml /usr/share/filebeat/filebeat.yml
RUN  chown filebeat /usr/share/filebeat/filebeat.yml && chmod go-w /usr/share/filebeat/filebeat.yml 
USER filebeat