filebeat.inputs:
- type: log
  paths:
  - "/usr/share/filebeat/logfile.log"
  fields_under_root: true
  
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"