heartbeat.config.monitors:
  path: /usr/share/heartbeat/heartbeat.monitors.yml
  reload.enabled: true
  reload.period: 1s

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"